name: passwords
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  